---
title: Scratch coördinaten
hero_image: images/banner.png
description: Meer informatie over coördinaten in Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - title: Scratch coördinaten
