---
title: Scratch निर्देशांक
hero_image: images/banner.png
description: Scratch में निर्देशांकों के बारे में सीखें
listed: false
ingredient: true
copyedit: false
steps:
  - title: Scratch निर्देशांक
