---
title: Scratch ஆயத்தொலைகள்
hero_image: படங்கள்/banner.png
description: Scratch-இல் உள்ள ஆயத்தொலைகள்(coordinates) பற்றி அறியவும்
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Scratch ஆயத்தொலைகள்
