---
title: Tha sgrìob a 'co-òrdanachadh
hero_image: images / banner.png
description: Ionnsaich mu cho-chomharran ann an Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Tha sgrìob a 'co-òrdanachadh
