---
title: Comhordaíonn Scratch
hero_image: íomhánna / banner.png
description: Foghlaim faoi chomhordanáidí i Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Comhordaíonn Scratch
