---
title: Kordinati mill-Grif
hero_image: stampi / banner.png
description: Tgħallem dwar il-koordinati fi Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Kordinati mill-Grif
