---
title: Coordenadas do Scratch
hero_image: images/banner.png
description: Aprende acerca das coordenadas no Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Coordenadas do Scratch
