---
title: Координатите на надраскване
hero_image: изображения / banner.png
description: Научете повече за координатите на Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Координатите на надраскване
