---
title: Koordinate u Scratchu
hero_image: images/banner.png
description: Saznaj više o koordinatama u Scratchu
listed: false
ingredient: true
copyedit: false
steps:
  - title: Koordinate u Scratchu
