---
title: Scratch koordinaatit
hero_image: images/banner.png
description: Lisätietoja koordinaateista Scratchissa
listed: false
ingredient: true
copyedit: false
steps:
  - title: Scratch koordinaatit
