---
title: Mga coordinates ng Scratch
hero_image: images/banner.png
description: Alamin ang mga coordinates ng Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - title: Mga coordinates ng scratch
