---
title: Coordenadas en Scratch
hero_image: images/banner.png
description: Aprende sobre las coordenadas en Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - title: Coordenadas en Scratch
