---
title: Scratch-Koordinaten
hero_image: images/banner.png
description: Erfahre mehr über Koordinaten in Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Scratch-Koordinaten
