---
title: Coordonatele Scratch
hero_image: images / banner.png
description: Învățați despre coordonate în Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Coordonate Scratch
