---
title: Coordonatele Scratch
hero_image: images/banner.png
description: Învață despre coordonate în Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Coordonatele Scratch
