---
title: Coordenadas no Scratch
hero_image: images/banner.png
description: Saiba mais sobre coordenadas no Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Coordenadas no Scratch
