---
title: Koordinat Scratch
hero_image: images/banner.png
description: Mempelajari tentang koordinat pada Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Koordinat Scratch
