---
title: Coordenades de scratch
hero_image: imatges / banner.png
description: Obteniu informació sobre les coordenades a Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Coordenades de scratch
