---
title: Scratch souřadnice
hero_image: obrázky / banner.png
description: Další informace o souřadnicích v aplikaci Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Scratch souřadnice
