---
title: Scratchi koordinaadid
hero_image: images/banner.png
description: Õpi Scratchi koordinaatide kohta
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Scratchi koordinaadid
