---
title: Scratch-koordinaadid
hero_image: images / banner.png
description: Lugege koordinaatide kohta nullist
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Scratch-koordinaadid
