---
title: Współrzędne w Scratchu
hero_image: images / banner.png
description: Dowiedz się więcej o współrzędnych w Scratchu
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Współrzędne w Scratchu
