---
title: Koordinat Scratch
hero_image: imej / banner.png
description: Ketahui mengenai koordinat dalam Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Koordinat Scratch
