---
title: Koordinate u Scratch-u
hero_image: images/banner.png
description: Saznaj o koordinatama u Scratch-u
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Koordinate u Scratch-u
