---
title: Les coordonnées dans Scratch
hero_image: images/banner.png
description: En savoir plus sur les coordonnées dans Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Les coordonnées dans Scratch
