---
title: Coordinate di Scratch
hero_image: images/banner.png
description: Scopri le coordinate di Scratch
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Coordinate di Scratch
