---
title: Scratch koordinatları
hero_image: images / banner.png
description: Scratch'teki koordinatlar hakkında bilgi edinin
listed: false
ingredient: true
copyedit: false
steps:
  - 
    title: Scratch koordinatları
